FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY app/pyrometers/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app/shared/device-common.css .
COPY app/pyrometers/ .

ENV PYTHONUNBUFFERED=1
CMD ["python", "pyrometers_app.py"]

